apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  namespace: 12-factor-app
  name: burn-cpu-100
spec:
  selector:
    namespaces:
      - 12-factor-app
    labelSelectors:
      app.kubernetes.io/instance: 12-factor-app
  mode: all
  stressors:
    cpu:
      workers: 1
      load: 100
  duration: 30s
