apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-corrupt-example
  namespace: 12-factor-app
spec:
  action: corrupt
  mode: all
  selector:
    namespaces:
      - 12-factor-app
    labelSelectors:
      app.kubernetes.io/instance: 12-factor-app
  corrupt:
    corrupt: "40"
    correlation: "25"
  duration: "10s"
