apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-bandwidth-100kbps
  namespace: 12-factor-app
spec:
  action: bandwidth
  mode: all
  selector:
    namespaces:
      - 12-factor-app
    labelSelectors:
      app.kubernetes.io/instance: 12-factor-app
  bandwidth:
    rate: 100kbps
    limit: 100
    buffer: 10000
    peakrate: 1000000
    minburst: 1000000
  duration: "10s"