apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  namespace: 12-factor-app
  name: scheduled-pod-failure
spec:
  schedule: 5 * * * *
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: 2
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - 12-factor-app
      labelSelectors:
        app: controller
    mode: one
    action: pod-failure
    duration: 1m
    gracePeriod: 0
