# apiVersion: jaegertracing.io/v1
# kind: Jaeger
# metadata:
#   name: simplest
#   namespace: observability

apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:latest
    options:
      log-level: debug
      query:
        base-path: /jaeger
      prometheus:
        server-url: "http://prom.<ENV-NAME>-<ENV-USER-ID>-01.<ENV-ANIMAL>.<ENV-DOMAIN>"
    metricsStorage:
      type: prometheus
  storage:
    options:
      memory:
        max-traces: 100000
