image:
  tag: "v3.0.0-beta3"
logs:
  access:
    enabled: true
metrics:
  # prometheus: null
  openTelemetry:
    ## Address of the OpenTelemetry Collector to send metrics to.
    address: "otel-dapr-collector.opentelemetry:4317"
    ## Enable metrics on entry points.
    addEntryPointsLabels: true
    ## Enable metrics on routers.
    addRoutersLabels: true
    ## Enable metrics on services.
    addServicesLabels: true
    ## Explicit boundaries for Histogram data points.
    explicitBoundaries:
      - "0.1"
      - "0.3"
      - "1.2"
      - "5.0"
    ## Allows reporter to send metrics to the OpenTelemetry Collector without using a secured protocol.
    insecure: true
    ## Interval at which metrics are sent to the OpenTelemetry Collector.
    pushInterval: 10s
    ## This instructs the reporter to send metrics to the OpenTelemetry Collector using gRPC.
    grpc: true
tracing:
  openTelemetry:
    grpc: true
    insecure: true
    address: otel-dapr-collector.opentelemetry:4317