apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: controller-ingress
  namespace: 12-factor-app
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`12factor.<ENV-NAME>-<ENV-USER-ID>-01.<ENV-ANIMAL>.<ENV-DOMAIN>`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: controller
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dapr-dashboard-ingress
  namespace: dapr-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dapr.<ENV-NAME>-<ENV-USER-ID>-01.<ENV-ANIMAL>.<ENV-DOMAIN>`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: dapr-dashboard
          port: 8080
