name: Containers - distributed-calendar

on:
  push:
    branches: [ 'main' ]
    paths: [ 'go/**', 'node/**', 'python/**' ]
  pull_request:
    branches: [ 'main' ]
    paths: [ 'go/**', 'node/**', 'python/**' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        container: [ go, node, python ]
    uses: infralovers/.github/.github/workflows/container.yml@main
    secrets:
      QUAY_USER: "${{ fromJSON(secrets.VAULT_KV_1D187965_OP_QUAY_ROBOT_ACCOUNT).username }}"
      QUAY_TOKEN: "${{ fromJSON(secrets.VAULT_KV_1D187965_OP_QUAY_ROBOT_ACCOUNT).password }}"
      BOT_ACCESS_TOKEN: "${{ fromJSON(secrets.VAULT_KV_1D187965_OP_GITHUB_INFRALOVERS).PAT }}"
      MONDOO_SERVICE_ACCOUNT: "${{ fromJson(secrets.VAULT_KV_1D187965_OP_MONDOO_PACKER_AGENT).password }}"
    with:
      dockerfile: "${{ matrix.container }}/Dockerfile"
      score: 50
      platforms: "linux/amd64, linux/arm64"
      release: false
